# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXoAcz9yy0z-pVMREGttc3QaMZqbN7U3

!pip install streamlit
"""


import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.metrics.pairwise import cosine_similarity
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import load_model

encoder_model = load_model('incident_encoder_model.h5')

with open('tokenizer.pickle', 'rb') as f:
  tokenizer = pickle.load(f)

with open('tokenizer.pickle', 'rb') as f:
  tokenizer = pickle.load(f)

with open('max_len.pickle', 'rb') as f:
  max_len = pickle.load(f)

with open('incident_embeddings.pickle', 'rb') as f:
  incident_embeddings = pickle.load(f)

with open('training_data.pickle', 'rb') as f:
  X_train = pickle.load(f)

with open('resolution_data.pickle', 'rb') as f:
  y_train = pickle.load(f)

st.title("Incident Resolution Recommender System")
query = st.text_input("Incident Description")

# ==============================
# Recommendation Function
# ==============================

def recommend_resolution(query, top_k=3):

    seq = tokenizer.texts_to_sequences([query])
    padded = pad_sequences(seq, maxlen=max_len, padding='post')

    query_embedding = encoder_model.predict(padded)

    similarity = cosine_similarity(query_embedding, incident_embeddings)[0]
    print("Similarity", similarity.argsort()[-top_k:][::-1])

    top_indices = similarity.argsort()[-top_k:][::-1]

    results = []

    for idx in top_indices:
        results.append({
            "Incident": tokenizer.sequences_to_texts([X_train[idx]])[0], # Convert sequence back to text
            "Resolution": y_train.iloc[idx],
            "Similarity": similarity[idx]
        })

    return pd.DataFrame(results)

# ==============================
# 9. Test Recommendation
# ==============================

results = recommend_resolution(query)

st.write("Top 3 Recommendations:")
st.write(results)

